In [3]:
import numpy as np

# Numpy Basics

# Numpy Arrays

In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(arr1), arr1.shape, arr1.dtype

(numpy.ndarray, (2, 3), dtype('int32'))

In [8]:
arr1.min(), arr1.max(), arr1.mean(), arr1.std(), arr1.sum()

(1, 6, 3.5, 1.707825127659933, 21)

## Array Indexing

In [10]:
arr1[0], arr1[1]

(array([1, 2, 3]), array([4, 5, 6]), 1, 2, 4)

In [11]:
arr1[0, 0], arr1[0, 1], arr1[1, 0]

(1, 2, 4)

In [12]:
arr1[0][0], arr1[0][1], arr1[1][0]

(1, 2, 4)

In [14]:
arr1[arr1 > 2]

array([3, 4, 5, 6])

## Array Reshape

`.T`/`.transpose()` 메소드는 전치행렬을 구한다.

In [17]:
arr1.T, arr1.transpose()

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

`.flatten()` 메소드는 다차원 배열을 1차원으로 평탄화시킬 때 사용한다.

In [18]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6])

## Array Calculations

In [19]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [21]:
arr1 + arr2, np.add(arr1, arr2)

(array([[ 8, 10, 12],
        [14, 16, 18]]),
 array([[ 8, 10, 12],
        [14, 16, 18]]))

In [22]:
arr1 - arr2, np.subtract(arr1, arr2)

(array([[-6, -6, -6],
        [-6, -6, -6]]),
 array([[-6, -6, -6],
        [-6, -6, -6]]))

In [24]:
arr1 * arr2, np.multiply(arr1, arr2) # element-wise multiplication

(array([[ 7, 16, 27],
        [40, 55, 72]]),
 array([[ 7, 16, 27],
        [40, 55, 72]]))

In [25]:
arr1 / arr2, np.divide(arr1, arr2) # element-wise division

(array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]),
 array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]))

In [31]:
arr1.dot(arr2.T) # matrix multiplication/dot product

array([[ 50,  68],
       [122, 167]])

## Broadcasting

브로드캐스팅 : 행렬 크기가 달라도 연산 가능하도록 작은 행렬 확장.
배수 사이즈 행렬이어야 가능.

In [28]:
arr3 = np.array([[1, 2, 3]])
arr1 + arr3

array([[2, 4, 6],
       [5, 7, 9]])

# Numpy Functions